require "fileutils"

namespace :solidstats do
  desc "Clean up all JSON files and caches generated by Solidstats"
  task :clean do
    solidstats_dir = Rails.root.join('solidstats')

    if Dir.exist?(solidstats_dir)
      puts "Removing Solidstats data directory: #{solidstats_dir}"
      FileUtils.rm_rf(solidstats_dir)
      puts "Solidstats data cleaned."
    else
      puts "Solidstats data directory not found, nothing to clean."
    end
  end
end
