name: Ruby Gem Tests

on:
  push:
    branches: [ main, master, development ]
  pull_request:
    branches: [ main, master, development ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2']
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # This will run `bundle install` and cache the result automatically
    
    - name: Ensure bundler is not in frozen mode
      run: |
        bundle config set --local frozen false
    
    - name: Install dependencies
      run: bundle install
      
    - name: Run tests
      run: bundle exec rake test
